spring.application.name=aijavadevs
server.port=8081

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=${OPENAI_BASE_URL}
spring.ai.openai.chat.options.model=${OPENAI_CHAT_MODEL}



spring.datasource.url=jdbc:postgresql://localhost:5433/ai_knowledge
spring.datasource.username=admin
spring.datasource.password=secret

# Tell Spring AI to initialize the pgvector schema on startup
spring.ai.vectorstore.pgvector.initialize-schema=true
